kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: nomApp
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 443
      clusterIP: 10.27.240.1
      loadBalancerIP:
      type: LoadBalancer
      status:
        loadBalancer:
          ingress:
            - ip: 146.148.47.155
